import './globals.css';
import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts';
import Header from './ui/header/header';

export const metadata: Metadata = {
  title: 'Events Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
